########################################################################
## Travis CI config for Pothos
##
## * not all components will be configured
## * the matrix builds Release and Debug
## * run the self tests after install
########################################################################

sudo: required
dist: trusty

language: cpp
compiler: gcc

env:
  global:
    - INSTALL_PREFIX=/usr/local
    - SOAPY_SDR_BRANCH=master
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

# whitelist
branches:
  only:
    - master
    - maint

before_install:
  # regular ubuntu packages
  - sudo add-apt-repository main
  - sudo add-apt-repository universe

  # development files from ppa
  - sudo add-apt-repository -y ppa:myriadrf/drivers
  - sudo add-apt-repository -y ppa:pothosware/support
  - sudo add-apt-repository -y ppa:pothosware/framework

  # update after package changes
  - sudo apt-get update

install:
  # install development dependencies
  - sudo apt-get install -qq libnuma-dev cmake

  # install development dependencies from drivers ppa
  - sudo apt-get install -qq libspuce-dev libsoapysdr-dev

  # install development dependencies from support ppa
  - sudo apt-get install -qq libpoco-dev-min libmuparserx-dev

  # install development dependencies from framework ppa
  - sudo apt-get install -qq libpothos-serialization-dev

  # install audio support dependencies
  - sudo apt-get install -qq portaudio19-dev libjack-jackd2-dev

  # install graphics support dependencies
  - sudo apt-get install -qq qtbase5-dev libqt5svg5-dev libqwt-qt5-dev

  # install python support dependencies
  - sudo apt-get install -qq python-dev python-numpy

  # install SoapySDR from source
  - git clone https://github.com/pothosware/SoapySDR.git
  - pushd SoapySDR
  - git checkout ${SOAPY_SDR_BRANCH}
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make && sudo make install
  - popd

script:
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DPYTHON_EXECUTABLE=/usr/bin/python2 -DPython_ADDITIONAL_VERSIONS=2.7
  - make -j2
  - sudo make install

  # setup environment paths
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}
  - export PATH=${INSTALL_PREFIX}/bin:${PATH}
  - export PYTHONPATH=/usr/lib/python2.7/dist-packages:${PYTHONPATH}
  - export PYTHONPATH=${INSTALL_PREFIX}/lib/python2.7/dist-packages:${PYTHONPATH}

  # basic test for command line utility
  - PothosUtil --system-info
  - PothosUtil --self-tests
