########################################################################
## Travis CI config for Pothos
##
## * not all components will be configured
## * the matrix builds Release and Debug
## * run the self tests after install
########################################################################

sudo: required
dist: trusty

language: cpp
compiler: gcc

env:
  global:
    - INSTALL_PREFIX=/usr/local
    - SOAPY_SDR_BRANCH=master
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

# whitelist
branches:
  only:
    - master

before_install:
  # regular ubuntu packages
  - sudo add-apt-repository main
  - sudo add-apt-repository universe

  # poco and qwt development files from ppa
  - sudo add-apt-repository -y ppa:pothosware/support

  # update after package changes
  - sudo apt-get update

install:
  # install development dependencies
  - sudo apt-get install -qq libnuma-dev cmake libpoco-dev-min

  # install audio support dependencies
  - sudo apt-get install -qq portaudio19-dev libjack-jackd2-dev

  # install graphics support dependencies
  - sudo apt-get install -qq qtbase5-dev libqt5svg5-dev libqwt-qt5-dev

  # install python support dependencies
  - sudo apt-get install -qq python-dev python-numpy

  # install SoapySDR from source
  - git clone https://github.com/pothosware/SoapySDR.git
  - pushd SoapySDR
  - git checkout ${SOAPY_SDR_BRANCH}
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make && sudo make install
  - popd

script:
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DENABLE_PYTHON=OFF
  - make -j2
  - sudo make install

  # setup environment paths
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}
  - export PATH=${INSTALL_PREFIX}/bin:${PATH}
  - export PYTHONPATH=/usr/lib/python2.7/dist-packages:${PYTHONPATH}
  - export PYTHONPATH=${INSTALL_PREFIX}/lib/python2.7/dist-packages:${PYTHONPATH}

  # basic test for command line utility
  - PothosUtil --system-info
  - PothosUtil --self-tests
